return {
  filetypes = {
    "c",
    "css",
    "gitcommit",
    "go",
    "haskell",
    "html",
    "java",
    "javascript",
    "javascriptreact",
    "lua",
    "markdown",
    "php",
    "python",
    "ruby",
    "rust",
    "swift",
    "toml",
    "text",
    "typescript",
    "typescriptreact",
    "zig",
  },
  root_markers = { ".git", "codebook.toml", ".codebook.toml" },
}
