---

repos:
  - repo: local
    hooks:
    - id: lua-format
      name: format lua
      description: format lua
      entry: lua-format --column-limit 150 -i
      language: system
      types: [file, lua]
