local utils = require("sh.utils")

utils.lsp_attach(function(_, bufnr)
  vim.keymap.set("n", "gD", vim.lsp.buf.declaration, { silent = true, buffer = bufnr })
  vim.keymap.set("n", "gd", vim.lsp.buf.definition, { silent = true, buffer = bufnr })
  vim.keymap.set("n", "gi", vim.lsp.buf.implementation, { silent = true, buffer = bufnr })
  vim.keymap.set("n", "gf", vim.lsp.buf.format, { silent = true, buffer = bufnr })
  vim.keymap.set("n", "gr", vim.lsp.buf.references, { silent = true, buffer = bufnr })
  vim.keymap.set("n", "gl", vim.lsp.buf.hover, { silent = true, buffer = bufnr })
  vim.keymap.set("n", "gk", vim.lsp.buf.signature_help, { silent = true, buffer = bufnr })
  vim.keymap.set("n", "<leader>ga", vim.lsp.buf.code_action, { silent = true, buffer = bufnr })
  --xmap({ "la", vim.lsp.buf.range_code_action, { silent = true, buffer = bufnr } })
  vim.keymap.set("n", "[d", vim.diagnostic.goto_prev, { silent = true, buffer = bufnr })
  vim.keymap.set("n", "]d", vim.diagnostic.goto_next, { silent = true, buffer = bufnr })
end)
