local wezterm = require("wezterm")

local colors = {
  ansi = {
    black = "#000000",
    red = "#f7768e",
    green = "#9ece6a",
    yellow = "#e0af68",
    blue = "#7aa2f7",
    magenta = "#bb9af7",
    cyan = "#7dcfff",
    white = "#a9b1d6",
  },
  brights = {
    black = "#414868",
    red = "#f7768e",
    green = "#9ece6a",
    yellow = "#e0af68",
    blue = "#7aa2f7",
    magenta = "#bb9af7",
    cyan = "#7dcfff",
    white = "#c0caf5",
  },
}

return {
  enable_wayland = true,
  front_end = "WebGpu",
  window_decorations = "INTEGRATED_BUTTONS|RESIZE",
  --window_decorations = "TITLE|RESIZE",
  window_padding = { left = 1, right = 1, top = 0, bottom = 1 },
  integrated_title_button_alignment = "Left",
  integrated_title_button_color = colors.ansi.red,
  integrated_title_buttons = { "Close" },
  max_fps = 144,
  hide_tab_bar_if_only_one_tab = false,
  enable_scroll_bar = false,
  use_fancy_tab_bar = false,
  --tab_bar_at_bottom = true,
  animation_fps = 1,
  colors = {
    background = colors.ansi.black,
    cursor_bg = colors.brights.white,
    cursor_border = colors.brights.white,
    cursor_fg = colors.ansi.black,
    foreground = colors.brights.white,
    selection_bg = colors.ansi.white,
    selection_fg = colors.ansi.black,
    split = colors.ansi.blue,
    compose_cursor = "#ff9e64",
    scrollbar_thumb = "#292e42",
    ansi = {
      colors.ansi.black,
      colors.ansi.red,
      colors.ansi.green,
      colors.ansi.yellow,
      colors.ansi.blue,
      colors.ansi.magenta,
      colors.ansi.cyan,
      colors.ansi.white,
    },
    brights = {
      colors.brights.black,
      colors.brights.red,
      colors.brights.green,
      colors.brights.yellow,
      colors.brights.blue,
      colors.brights.magenta,
      colors.brights.cyan,
      colors.brights.white,
    },
    tab_bar = {
      background = colors.ansi.black,
      active_tab = {
        bg_color = colors.ansi.cyan,
        fg_color = colors.ansi.black,
      },
      inactive_tab = {
        bg_color = colors.ansi.black,
        fg_color = colors.brights.white,
      },
      new_tab = {
        bg_color = colors.ansi.black,
        fg_color = colors.brights.white,
      },
    },
  },
  --dpi = 192,
  default_cursor_style = "BlinkingBar",
  xcursor_theme = "Adwaita",
  window_background_opacity = 0.900,
  warn_about_missing_glyphs = false,
  font = wezterm.font({
    -- family = "Liga SFMono Nerd Font",
    -- family = "Fira Code",
    -- family = "Cascadia Code",
    -- family = "JetBrains Mono",
    -- family = "Lilex",
    -- family = "NeoSpleen Nerd Font",
    family = "Hasklig",
    -- family = "0xProto Nerd Font",
    -- family = "Google Sans Regular",
    -- weight = 100,
    harfbuzz_features = { "calt=1", "clig=1", "liga=1" },
  }),
  font_size = 10,
  freetype_load_flags = "FORCE_AUTOHINT",
  exit_behavior = "Close",
  unzoom_on_switch_pane = true,
  leader = { key = "`", mods = "", timeout_milliseconds = 500 },
  keys = {
    { key = "`", mods = "LEADER", action = wezterm.action({ SendString = "`" }) },
    { key = "\\", mods = "LEADER", action = wezterm.action({ SplitHorizontal = { domain = "DefaultDomain" } }) },
    { key = "-", mods = "LEADER", action = wezterm.action({ SplitVertical = { domain = "DefaultDomain" } }) },
    { key = "c", mods = "LEADER", action = wezterm.action({ SpawnTab = "DefaultDomain" }) },
    { key = "j", mods = "LEADER", action = wezterm.action({ ActivatePaneDirection = "Next" }) },
    { key = "k", mods = "LEADER", action = wezterm.action({ ActivatePaneDirection = "Prev" }) },
    { key = "n", mods = "LEADER", action = wezterm.action({ ActivateTabRelative = 1 }) },
    { key = "p", mods = "LEADER", action = wezterm.action({ ActivateTabRelative = -1 }) },
    { key = "y", mods = "LEADER", action = wezterm.action.ActivateCopyMode },
  },
}
