local wezterm = require("wezterm")

local colors = {
  background = "#030302",
  foreground = "#d8d0c0",
  cursor_bg = "#e08060",
  cursor_fg = "#030302",
  ansi = {
    black = "#1c1b19",
    red = "#e08060",
    green = "#8a9868",
    yellow = "#c8b468",
    blue = "#7890a0",
    magenta = "#bb9af7",
    magenta = "#b07878",
    cyan = "#7dcfff",
    cyan = "#80a090",
    white = "#a9b1d6",
    white = "#d8d0c0",
  },
  brights = {
    black = "#3e3c38",
    red = "#e08060",
    green = "#8a9868",
    yellow = "#c8b468",
    blue = "#b07878",
    magenta = "#bb9af7",
    cyan = "#80a090",
    white = "#d8d0c0",
  },
}

return {
  enable_wayland = true,
  front_end = "WebGpu",
  window_decorations = "INTEGRATED_BUTTONS|RESIZE",
  --window_decorations = "TITLE|RESIZE",
  window_padding = { left = 1, right = 1, top = 0, bottom = 1 },
  integrated_title_button_alignment = "Left",
  integrated_title_button_color = colors.ansi.red,
  integrated_title_buttons = { "Close" },
  max_fps = 144,
  hide_tab_bar_if_only_one_tab = false,
  enable_scroll_bar = false,
  use_fancy_tab_bar = false,
  --tab_bar_at_bottom = true,
  animation_fps = 1,
  colors = {
    background = colors.background,
    cursor_bg = colors.cursor_bg,
    cursor_border = colors.cursor_border,
    cursor_fg = colors.ansi.black,
    foreground = colors.foreground,
    selection_bg = colors.selection_bg,
    selection_fg = colors.selection_fg,
    split = colors.ansi.magenta,
    --compose_cursor = "#ff9e64",
    --scrollbar_thumb = "#292e42",
    ansi = {
      colors.ansi.black,
      colors.ansi.red,
      colors.ansi.green,
      colors.ansi.yellow,
      colors.ansi.blue,
      colors.ansi.magenta,
      colors.ansi.cyan,
      colors.ansi.white,
    },
    brights = {
      colors.brights.black,
      colors.brights.red,
      colors.brights.green,
      colors.brights.yellow,
      colors.brights.blue,
      colors.brights.magenta,
      colors.brights.cyan,
      colors.brights.white,
    },
    tab_bar = {
      background = colors.ansi.black,
      active_tab = {
        bg_color = colors.ansi.cyan,
        fg_color = colors.ansi.black,
      },
      inactive_tab = {
        bg_color = colors.ansi.black,
        fg_color = colors.brights.white,
      },
      new_tab = {
        bg_color = colors.ansi.black,
        fg_color = colors.brights.white,
      },
    },
  },
  --dpi = 192,
  default_cursor_style = "BlinkingBar",
  window_background_opacity = 0.930,
  warn_about_missing_glyphs = false,
  font = wezterm.font({
    -- family = "Fira Code",
    -- family = "Cascadia Code",
    -- family = "JetBrains Mono",
    -- family = "Monaspace Neon",
    family = "VictorMono Nerd Font Mono",
    -- family = "Lilex",
    -- family = "NeoSpleen Nerd Font",
    -- family = "Hasklig",
    -- family = "Iosevka Term SS18",
    -- family = "Monaco",
    -- family = "0xProto Nerd Font",
    -- family = "Google Sans Regular",
    --weight = 400,
    --harfbuzz_features = { "calt=1", "clig=1", "liga=1" },
    harfbuzz_features = {
      "calt=1",
      "clig=1",
      "liga=1",
      "ss01=1",
      "ss02=1",
      "ss03=1",
      "ss04=1",
      "ss05=1",
      "ss06=1",
      "ss07=1",
      "ss08=1",
      "ss09=1",
      "ss10=1",
    },
  }),
  font_size = 10,
  freetype_load_flags = "FORCE_AUTOHINT",
  exit_behavior = "Close",
  unzoom_on_switch_pane = true,
  leader = { key = "`", mods = "", timeout_milliseconds = 500 },
  keys = {
    { key = "`", mods = "LEADER", action = wezterm.action({ SendString = "`" }) },
    { key = "\\", mods = "LEADER", action = wezterm.action({ SplitHorizontal = { domain = "DefaultDomain" } }) },
    { key = "-", mods = "LEADER", action = wezterm.action({ SplitVertical = { domain = "DefaultDomain" } }) },
    { key = "c", mods = "LEADER", action = wezterm.action({ SpawnTab = "DefaultDomain" }) },
    { key = "j", mods = "LEADER", action = wezterm.action({ ActivatePaneDirection = "Next" }) },
    { key = "k", mods = "LEADER", action = wezterm.action({ ActivatePaneDirection = "Prev" }) },
    { key = "n", mods = "LEADER", action = wezterm.action({ ActivateTabRelative = 1 }) },
    { key = "p", mods = "LEADER", action = wezterm.action({ ActivateTabRelative = -1 }) },
    { key = "y", mods = "LEADER", action = wezterm.action.ActivateCopyMode },
    { key = "1", mods = "LEADER", action = wezterm.action.ActivateTab(0) },
    { key = "2", mods = "LEADER", action = wezterm.action.ActivateTab(1) },
    { key = "3", mods = "LEADER", action = wezterm.action.ActivateTab(2) },
    { key = "4", mods = "LEADER", action = wezterm.action.ActivateTab(3) },
    { key = "5", mods = "LEADER", action = wezterm.action.ActivateTab(4) },
    { key = "6", mods = "LEADER", action = wezterm.action.ActivateTab(5) },
    { key = "7", mods = "LEADER", action = wezterm.action.ActivateTab(6) },
  },
}
