vim.filetype.add({ extension = { cr = 'crystal' } })
vim.filetype.add({ extension = { mk = 'make' } })
vim.filetype.add({ pattern = { ['Jenkinsfile*'] = 'groovy' } })
vim.filetype.add({ filename = { ['poetry.lock'] = 'toml' } })
vim.filetype.add({ pattern = { ['Dockerfile*'] = 'dockerfile' } })
vim.filetype.add({ filename = { ['poetry.lock'] = 'toml' } })
vim.filetype.add({ filename = { ['yarn.lock'] = 'yaml' } })
