palette.update({
    "background": ("black", "light gray"),
    "breakpoint focused source": ("black", "dark red"),
    "breakpoint source": ("yellow", "dark red"),
    "breakpoint": ("default", "default"),
    "button": ("white", "dark blue"),
    "current breakpoint focused source": ("white", "dark red"),
    "current breakpoint source": ("black", "dark red"),
    "current frame class": ("dark blue", "default"),
    "current frame location": ("light cyan", "default"),
    "current frame name": (add_setting("white", "bold"), "default"),
    "dialog title": (add_setting("white", "bold"), "dark cyan"),
    "fixed value": ("light gray", "dark blue"),
    "focused breakpoint": ("black", "dark green"),
    "focused button": ("light cyan", "black"),
    "focused current frame class": ("dark blue", "dark green"),
    "focused current frame location": ("light cyan", "dark green"),
    "focused current frame name": (add_setting("white", "bold"), "dark green", "bold"),
    "focused frame class": ("dark blue", "dark green"),
    "focused frame location": ("light cyan", "dark green"),
    "focused frame name": ("black", "dark green"),
    "focused highlighted var label": ("white", "dark green"),
    "focused highlighted var value": ("black", "dark green"),
    "focused return label": ("light gray", "dark blue"),
    "focused return label": ("light gray", "dark blue"),
    "focused return value": ("black", "dark green"),
    "focused return value": ("black", "dark green"),
    "focused selectable": ("black", "dark green"),
    "focused sidebar": ("yellow", "light gray", "standout"),
    "focused var label": ("dark blue", "dark green"),
    "focused var value": ("black", "dark green"),
    "frame class": ("dark blue", "default"),
    "frame location": ("light cyan", "default"),
    "frame name": ("white", "default"),
    "header": ("black", "light gray", "standout"),
    "highlighted var value": ("black", "dark cyan"),
    "hotkey": (add_setting("black", "underline"), "light gray", "underline"),
    "label": ("black", "light gray"),
    "return label": ("white", "dark blue"),
    "return label": ("white", "dark blue"),
    "return value": ("black", "dark cyan"),
    "return value": ("black", "dark cyan"),
    "search box": ("default", "default"),
    "search not found": ("white", "dark red"),
    "selectable": ("black", "dark cyan"),
    "stack": ("white", "default"),
    "value": ("yellow", "dark blue"),
    "var label": ("dark blue", "default"),
    "var value": ("white", "default"),
    "variable separator": ("dark cyan", "light gray"),
    "variables": ("white", "default"),
    "warning": (add_setting("white", "bold"), "dark red", "standout"),
    # highlighting
    "classname": ("dark cyan", "default"),
    "comment": ("dark green", "default"),
    "current focused source": ("white", "brown"),
    "current highlighted source": ("white", "dark cyan"),
    "current source": ("white", "light gray"),
    "focused source": ("black", "dark green"),
    "funcname": ("white", "default"),
    "highlighted source": ("white", "light cyan"),
    "keyword": ("dark magenta", "default"),
    "kw_namespace": ("dark magenta", "default"),
    "literal": ("dark cyan", "default"),
    "punctuation": ("white", "default"),
    "source": ("white", "default"),
    "string": ("light red", "default"),
})
