
- repo: Shougo/deoplete.nvim
  if: has('nvim')
  depends: [context_filetype.vim]
  hook_source: |
    let g:deoplete#enable_at_startup = 1
    let g:deoplete#auto_complete_delay = 60
    let g:deoplete#auto_refresh_delay = 1000
    let g:deoplete#enable_camel_case = 1
    let g:deoplete#tag#cache_limit_size = 5000000
    au CursorMovedI,InsertLeave * if pumvisible() == 0|silent! pclose|endif
    set completeopt=menu,preview,longest
    function! s:check_back_space() abort
        let col = col('.') - 1
        return !col || getline('.')[col-1] =~ '\s'
    endfunction
    imap <silent><expr> <TAB>
                \ pumvisible() ? "\<C-n>" :
                \ <SID>check_back_space() ? "\<TAB>" :
                \ deoplete#mappings#manual_complete()

- repo: Shougo/neocomplete
  if: ! has('nvim') && has('lua')
  on_event: InsertEnter

- repo: wellle/tmux-complete.vim
  depends: [deoplete.nvim]
  on_event: InsertEnter

