
- repo: pangloss/vim-javascript
  on_ft: javascript

- repo: carlitux/deoplete-ternjs
  build: npm install -g tern
  if: executable('npm') && has('nvim')
  on_i: 1
  on_ft: javascript
  hook_source: |
    let g:tern_request_timeout = 1
    let g:tern_show_signature_in_pum = '0'

- repo: mattn/emmet-vim
  on_i: 1
  on_ft: [css, html, jsx, javascript, javascript.jsx]
  hook_source: |
    let g:use_emmet_complete_tag = 0
    let g:user_emmet_install_global = 0
    let g:user_emmet_install_command = 0
    let g:user_emmet_mode = 'i'
    autocmd FileType html,css,jsx,javascript,javascript.jsx EmmetInstall | imap <buffer> <C-Return> <Plug>(emmet-expand-abbr)

