[tools]
aws-iam-authenticator = "latest"
awsls = "latest"
"github:looker-open-source/looker-cli" = "latest"
"github:vercel-labs/fx" = "latest"
herdr = "latest"
node = "latest"
"npm:@opencode-ai/cli" = { version = "beta", allow_builds = true }
"npm:pnpm" = "latest"
"pipx:harlequin" = { version = "latest", extras = "postgresql,mysql,s3" }
"pipx:mycli" = "latest"
"pipx:yawsso" = { version = "latest" }
trivy = "latest"
"github:redhat-et/ripwire" = "latest"
"github:hmans/beans" = "latest"

[settings]
trusted_config_paths = ["~/src/force/force-web/"]
experimental = true
dotfiles.root = "~/dotfiles"
dotfiles.default_mode = "symlink"

[dotfiles]
"~/.agents/skills" = { source = "~/dotfiles/.agents/skills" }
"~/.aliases" = {}
"~/.bashrc" = {}
"~/.claude/skills" = { source = "~/dotfiles/.agents/skills" }
"~/.config/direnv" = {}
"~/.config/ghostty" = {}
"~/.config/git" = {}
"~/.config/herdr/config.toml" = {}
"~/.config/mise" = {}
"~/.config/npm" = {}
"~/.config/nvim" = {}
"~/.config/opencode/cli.json" = {}
"~/.config/opencode/opencode.json" = {}
"~/.config/opencode/plugins/opencode-herdr" = { source = "~/dotfiles/.config/opencode/plugins/opencode-herdr" }
"~/.config/opencode/plugins/opencode-tmux" = { source = "~/dotfiles/.config/opencode/plugins/opencode-tmux" }
"~/.config/opencode/themes" = {}
"~/.config/opencode/tui.json" = {}
"~/.config/pacman" = {}
"~/.config/pgsqlrc" = {}
"~/.config/starship.toml" = {}
"~/.config/tmux" = {}
"~/.config/wezterm" = {}
"~/.gemrc" = {}
"~/.inputrc" = {}
"~/.local/bin" = {}
"~/.pdbrc" = {}
"~/.pdbrc.py" = {}
"~/.profile" = {}
"~/.zprofile" = {}
"~/.zshrc" = {}
